### ISSUE TITLE
Did I got the past version?

### ISSUE THREAD

**Issue by swbliss** [creativetimofficial/black-dashboard#9]
I have bought the library from "http://themes.getbootstrap.com/preview/?theme_id=8214&show_new=", but I think you upload past version of black dashboard.

There are some parts which work differently with previous live demo.

For example, the package said "Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"" (https://demos.creative-tim.com/marketplace/black-dashboard-pro/docs/1.0/getting-started/introduction.html#starter-template).
However it didn't work when I tried changing data-color.
I checked out _sidebar-and-main-panel.scss file, and realized that I have to use 'data' attribute to change the color from this part(_sidebar-and-main-panel.scss:365-370).
In addition, the border-top color is fixed as purple at _sidebar-and-main-panel.scss:491 which is different from livedemo.

Because the livedemo is supporting this kind of weird behavior correctly, I think you guys send me past version of black dashboard.

Thanks :)

**Comment by rarestoma** [comment]
Hello swbliss,

Thank you for the interest in our products.

You have the good version of black dashboard pro. The problem is that we didn't change a few things in documentation(like 'data' instead of 'data-color').
The $primary color is fixed for the main-panel and you can change it too using data attribute.

If I can help you with anything else, please let me know.

Best,
Rares
